// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: domain/auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URLPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Path   string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *URLPair) Reset() {
	*x = URLPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLPair) ProtoMessage() {}

func (x *URLPair) ProtoReflect() protoreflect.Message {
	mi := &file_domain_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLPair.ProtoReflect.Descriptor instead.
func (*URLPair) Descriptor() ([]byte, []int) {
	return file_domain_auth_proto_rawDescGZIP(), []int{0}
}

func (x *URLPair) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *URLPair) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type BlackWhiteList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleName string     `protobuf:"bytes,1,opt,name=ruleName,proto3" json:"ruleName,omitempty"`
	RuleType int32      `protobuf:"varint,2,opt,name=ruleType,proto3" json:"ruleType,omitempty"`
	Urls     []*URLPair `protobuf:"bytes,3,rep,name=urls,proto3" json:"urls,omitempty"`
	Ip       string     `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Enable   bool       `protobuf:"varint,5,opt,name=enable,proto3" json:"enable,omitempty"`
}

func (x *BlackWhiteList) Reset() {
	*x = BlackWhiteList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlackWhiteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackWhiteList) ProtoMessage() {}

func (x *BlackWhiteList) ProtoReflect() protoreflect.Message {
	mi := &file_domain_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackWhiteList.ProtoReflect.Descriptor instead.
func (*BlackWhiteList) Descriptor() ([]byte, []int) {
	return file_domain_auth_proto_rawDescGZIP(), []int{1}
}

func (x *BlackWhiteList) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *BlackWhiteList) GetRuleType() int32 {
	if x != nil {
		return x.RuleType
	}
	return 0
}

func (x *BlackWhiteList) GetUrls() []*URLPair {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *BlackWhiteList) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BlackWhiteList) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

// 微服务鉴权规则
type ServiceAuthRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace   string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ServiceName string            `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	BwConfigs   []*BlackWhiteList `protobuf:"bytes,3,rep,name=bwConfigs,proto3" json:"bwConfigs,omitempty"`
	Enable      bool              `protobuf:"varint,6,opt,name=enable,proto3" json:"enable,omitempty"`
	CreateTime  int64             `protobuf:"varint,7,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime  int64             `protobuf:"varint,8,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
}

func (x *ServiceAuthRule) Reset() {
	*x = ServiceAuthRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceAuthRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAuthRule) ProtoMessage() {}

func (x *ServiceAuthRule) ProtoReflect() protoreflect.Message {
	mi := &file_domain_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAuthRule.ProtoReflect.Descriptor instead.
func (*ServiceAuthRule) Descriptor() ([]byte, []int) {
	return file_domain_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceAuthRule) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServiceAuthRule) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceAuthRule) GetBwConfigs() []*BlackWhiteList {
	if x != nil {
		return x.BwConfigs
	}
	return nil
}

func (x *ServiceAuthRule) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *ServiceAuthRule) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ServiceAuthRule) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

var File_domain_auth_proto protoreflect.FileDescriptor

var file_domain_auth_proto_rawDesc = []byte{
	0x0a, 0x11, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x22, 0x35, 0x0a, 0x07, 0x55, 0x52, 0x4c, 0x50, 0x61,
	0x69, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x91,
	0x01, 0x0a, 0x0e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x75, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x72, 0x75, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x75, 0x72, 0x6c,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x52, 0x4c,
	0x50, 0x61, 0x69, 0x72, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x22, 0xdb, 0x01, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x75,
	0x74, 0x68, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x62, 0x77, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x42,
	0x6c, 0x61, 0x63, 0x6b, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x09, 0x62,
	0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x42, 0x23, 0x0a, 0x1a, 0x63, 0x6f, 0x6d, 0x2e, 0x6a, 0x64, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x6a, 0x6d, 0x73, 0x66, 0x2e, 0x70, 0x62, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x50, 0x01,
	0x5a, 0x03, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_domain_auth_proto_rawDescOnce sync.Once
	file_domain_auth_proto_rawDescData = file_domain_auth_proto_rawDesc
)

func file_domain_auth_proto_rawDescGZIP() []byte {
	file_domain_auth_proto_rawDescOnce.Do(func() {
		file_domain_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_domain_auth_proto_rawDescData)
	})
	return file_domain_auth_proto_rawDescData
}

var file_domain_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_domain_auth_proto_goTypes = []interface{}{
	(*URLPair)(nil),         // 0: v1.URLPair
	(*BlackWhiteList)(nil),  // 1: v1.BlackWhiteList
	(*ServiceAuthRule)(nil), // 2: v1.ServiceAuthRule
}
var file_domain_auth_proto_depIdxs = []int32{
	0, // 0: v1.BlackWhiteList.urls:type_name -> v1.URLPair
	1, // 1: v1.ServiceAuthRule.bwConfigs:type_name -> v1.BlackWhiteList
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_domain_auth_proto_init() }
func file_domain_auth_proto_init() {
	if File_domain_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_domain_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlackWhiteList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceAuthRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_domain_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_auth_proto_goTypes,
		DependencyIndexes: file_domain_auth_proto_depIdxs,
		MessageInfos:      file_domain_auth_proto_msgTypes,
	}.Build()
	File_domain_auth_proto = out.File
	file_domain_auth_proto_rawDesc = nil
	file_domain_auth_proto_goTypes = nil
	file_domain_auth_proto_depIdxs = nil
}
